### ISSUE TITLE
Switch to Zola

### ISSUE THREAD

**Issue by phansch** [phansch/phansch.net#189]
## Preparation

All the things that can be done before the actual switch

* [x] #190 Find a way to make the feature test suite work without `rack-jekyll`
* [x] #199 #200 #201 Move from Travis CI to Github Actions
* [x] #192 Add the post path to the frontmatter of every post
* [x] #196 Make sure emojis still work
* [x] #198 Wrap posts frontmatter strings in doublequotes (will ease migration to TOML frontmatter)

## Final migration

This is the actual migration to Zola.

* [x] Figure out the template structure
* [x] Move posts to `./content/posts` (`mv ../phansch.github.com/_posts content/posts`)
* [x] Move `archive` to `./content/archive/index.md` (`mv ../phansch.github.com/archive/index.md content/archive.md`)
* [x] Move `onehundred` to `./content/onehundred/rust.md` (`mv ../phansch.github.com/onehundred content/onehundred`)
* [x] Move `thanks` to `./content/thanks/index.md` (`mv ../phansch.github.com/thanks/index.md content/thanks.md`)
* [x] Move `reading` to `./content/reading/index.md` (`mv ../phansch.github.com/reading.md content/reading.md`)
* [x] Move `writing` to `./content/writing/index.md` (`mv ../phansch.github.com/writing.md content/writing/index.md`)
* [x] Move `slides`
* [x] Move `portfolio`
* [x] Migrate frontmatter to toml
* [x] Update `codespell` invocation in `script/ci.rb`
* [x] Update `html-proofer` invocation in `script/ci.rb`
* [x] Replace `{% highlight %}` usage
* [x] Make RSS work
* [x] robots.txt
* [x] Move assets
* [x] Update instructions in README
* [x] Check formatting in all posts and pages
* [x] ???
* [x] Replace phansch.github.com with the contents of this repo
